-- Generated by makeColors.sh. Modifications will be overwritten by next run
module Colors (
  color1, color2, color3, color4, color5
) where

color1, color2, color3, color4, color5 :: String
color1 = "#eac440"
color2 = "#351409"
color3 = "#d0902f"
color4 = "#a15501"
color5 = "%color5%"
