name:                xmonadrc
version:             0.16
synopsis:            My xmonad configuration.

ghc-options:
  -Wall
  -Wcompat
  -Wincomplete-record-updates
  -Wincomplete-uni-patterns
  -Wredundant-constraints
  -O2

dependencies:
  - base
  - containers
  - unix
  - xmonad
  - xmonad-contrib >= 0.17
  - X11
  - X11-xft        >= 0.3.4
  - utf8-string
  - directory
  - mtl
  - hip

executables:
  xmonadrc:
    source-dirs: src
    main: xmonad.hs

